apiVersion: v1
kind: Pod
metadata:
  labels:
    qos.coreweave.cloud/latency: low
  name: ak-trainer-1
spec:
  volumes:
    - name: storage-reward-models
      persistentVolumeClaim:
        claimName: storage-reward-models
  imagePullSecrets:
    - name: docker-creds
  containers:
    - name: bot-test-container
      image: ghcr.io/coreweave/ml-containers/torch-nccl:7ed4925
      imagePullPolicy: Always
      command: [ "/bin/sh" ]
      args: [ "-c", "echo '1' > /tmp/ready && sleep infinity" ]
      resources:
        limits:
          cpu: "48"
          nvidia.com/gpu: "4"
          memory: 512Gi
        requests:
          cpu: "48"
          nvidia.com/gpu: "4"
          memory: 512Gi
      volumeMounts:
        - name: storage-reward-models
          mountPath: /models
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        failureThreshold: 1
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_NVLINK_80GB
                  - A100_PCIE_80GB
                  - A100_NVLINK
                  - A100_PCIE_40GB
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 40
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_NVLINK_80GB
        - weight: 30
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_80GB
        - weight: 20
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_NVLINK
        - weight: 10
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_40GB